# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cwf < Formula
  desc "Copy and paste with friends remotely and easy"
  homepage "https://github.com/noobcollective/cwf"
  version "0.4.1"
  license "MIT"

  depends_on "go"

  on_macos do
    on_intel do
      url "https://github.com/noobcollective/cwf/releases/download/v0.4.1/cwf_0.4.1_darwin_amd64.tar.gz"
      sha256 "a76c2edbc8327abb5514211c2f186ff2ebb368a1362764a239d28a2de42630a3"

      def install
        bin.install "cwf"
      end
    end
    on_arm do
      url "https://github.com/noobcollective/cwf/releases/download/v0.4.1/cwf_0.4.1_darwin_arm64.tar.gz"
      sha256 "3f6ef2181d6ee0195bd84b3fbe1b489c3edabcbe0d5786273745b6809bfbbe76"

      def install
        bin.install "cwf"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/noobcollective/cwf/releases/download/v0.4.1/cwf_0.4.1_linux_amd64.tar.gz"
        sha256 "bb08d381235cd2e8737c2cbb0f8db5d088f7fca797e0a3d4edc918af777d9be0"

        def install
          bin.install "cwf"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/noobcollective/cwf/releases/download/v0.4.1/cwf_0.4.1_linux_armv6.tar.gz"
        sha256 "6c8aa9820365bb8168acd9d5856af155c9480758e1a18f87e855962470f5262a"

        def install
          bin.install "cwf"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/noobcollective/cwf/releases/download/v0.4.1/cwf_0.4.1_linux_arm64.tar.gz"
        sha256 "5c2879cd206ae393af9cfd02aab020305adba1fbd86ec5162e4119c6133af255"

        def install
          bin.install "cwf"
        end
      end
    end
  end
end
