# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cwf < Formula
  desc "Copy and paste with friends remotely and easy"
  homepage "https://github.com/noobcollective/cwf"
  version "0.4"
  license "MIT"

  depends_on "go"

  on_macos do
    on_intel do
      url "https://github.com/noobcollective/cwf/releases/download/v0.4/cwf_0.4_darwin_amd64.tar.gz"
      sha256 "4fefac3bb01499db029276d71a029edc50d98a612aa4cdf4b11792185b710321"

      def install
        bin.install "cwf"
      end
    end
    on_arm do
      url "https://github.com/noobcollective/cwf/releases/download/v0.4/cwf_0.4_darwin_arm64.tar.gz"
      sha256 "88bb92e10d43c32aea8a0016e0a9feb6b5a5c845c799e862a633801da780ef87"

      def install
        bin.install "cwf"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/noobcollective/cwf/releases/download/v0.4/cwf_0.4_linux_amd64.tar.gz"
        sha256 "cb6a3ce4afa2547aaa1a15e6702efc256778f123d02f72523ae49de7b3cf51d5"

        def install
          bin.install "cwf"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/noobcollective/cwf/releases/download/v0.4/cwf_0.4_linux_armv6.tar.gz"
        sha256 "ed199953131178a49fc2d53476bb3262c145bf5c69533859b2c1e5c29499f23a"

        def install
          bin.install "cwf"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/noobcollective/cwf/releases/download/v0.4/cwf_0.4_linux_arm64.tar.gz"
        sha256 "085b1561a44229f607c3996218bdf2356d21165fd3e302e4fda2f663b458dcbc"

        def install
          bin.install "cwf"
        end
      end
    end
  end
end
