# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reme < Formula
  desc "Setup up reminders easily in your terminal."
  homepage "https://github.com/noobcollective/reme"
  version "0.1"
  license "MIT"

  depends_on "go"

  on_macos do
    on_intel do
      url "https://github.com/noobcollective/reme/releases/download/v0.1/reme_0.1_darwin_amd64.tar.gz"
      sha256 "aa7002800a75dfd5c8be02ff7ed0861f5fab36d381e8b1a58b9945e6bb0ec7fc"

      def install
        bin.install "reme"
      end
    end
    on_arm do
      url "https://github.com/noobcollective/reme/releases/download/v0.1/reme_0.1_darwin_arm64.tar.gz"
      sha256 "9a9be90bf559683f3e3a63d1ba9aaf12604daff89b7d34f87271a3caf2e078ac"

      def install
        bin.install "reme"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/noobcollective/reme/releases/download/v0.1/reme_0.1_linux_amd64.tar.gz"
        sha256 "205ef223e7cb07f644d659ca934224a765b88a0d452dad32f00036668ee42828"

        def install
          bin.install "reme"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/noobcollective/reme/releases/download/v0.1/reme_0.1_linux_armv6.tar.gz"
        sha256 "ce8d2e82b947824e9a75cdcd46722bad0fa73b11e14c7be00e3ce9a471a5c789"

        def install
          bin.install "reme"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/noobcollective/reme/releases/download/v0.1/reme_0.1_linux_arm64.tar.gz"
        sha256 "f921f9cdee8e3be2a99242c6b8d1e9b7673810d1cd22547f9d128a22ccc77cb6"

        def install
          bin.install "reme"
        end
      end
    end
  end
end
