# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reme < Formula
  desc "Setup up reminders easily in your terminal."
  homepage "https://github.com/noobcollective/reme"
  version "0.1.1"
  license "MIT"

  depends_on "go"

  on_macos do
    on_intel do
      url "https://github.com/noobcollective/reme/releases/download/v0.1.1/reme_0.1.1_darwin_amd64.tar.gz"
      sha256 "a3a16ceae8fbfb6aca23cbb1ac305001e5375aecc99a0eeaf76434209c16e3cd"

      def install
        bin.install "reme"
      end
    end
    on_arm do
      url "https://github.com/noobcollective/reme/releases/download/v0.1.1/reme_0.1.1_darwin_arm64.tar.gz"
      sha256 "af511c277b8bd00b69f2515e417d07f1df2361e98fdd232037c48693fe4beb2f"

      def install
        bin.install "reme"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/noobcollective/reme/releases/download/v0.1.1/reme_0.1.1_linux_amd64.tar.gz"
        sha256 "647f07d08ede75b542dc9d44285c94ee556347d535b661c9a91536ae8c17dc5a"

        def install
          bin.install "reme"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/noobcollective/reme/releases/download/v0.1.1/reme_0.1.1_linux_armv6.tar.gz"
        sha256 "b6721afb79d0850ac876ab897028c61706defcbc5e76f83141c9174b0e1128f6"

        def install
          bin.install "reme"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/noobcollective/reme/releases/download/v0.1.1/reme_0.1.1_linux_arm64.tar.gz"
        sha256 "17f93b296dc2b756a9e18bd1c7847a7903f80b67f5702aa57e7f6c44a3022b69"

        def install
          bin.install "reme"
        end
      end
    end
  end
end
