# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reme < Formula
  desc "Setup up reminders easily in your terminal."
  homepage "https://github.com/noobcollective/reme"
  version "0.2.1"
  license "MIT"

  depends_on "go"

  on_macos do
    on_intel do
      url "https://github.com/noobcollective/reme/releases/download/v0.2.1/reme_0.2.1_darwin_amd64.tar.gz"
      sha256 "c2262ab30b5718690c5df4cfa53ac263ca3f2588f5ad4b457bc31ebe1a0d3356"

      def install
        bin.install "reme"
      end
    end
    on_arm do
      url "https://github.com/noobcollective/reme/releases/download/v0.2.1/reme_0.2.1_darwin_arm64.tar.gz"
      sha256 "d4bc4f6e14c9c58fa1ef2130e1b6d761c528f61e899157dbd5d76bfe3fa3c581"

      def install
        bin.install "reme"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/noobcollective/reme/releases/download/v0.2.1/reme_0.2.1_linux_amd64.tar.gz"
        sha256 "0309712134fd33686bb9497dff804b6badd6c463472716f6a18fe29ac578b5e0"

        def install
          bin.install "reme"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/noobcollective/reme/releases/download/v0.2.1/reme_0.2.1_linux_armv6.tar.gz"
        sha256 "2845c678069322a527b0eb1acbed2d09b98b645ed3ff3ae2d3cd577ce89bd863"

        def install
          bin.install "reme"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/noobcollective/reme/releases/download/v0.2.1/reme_0.2.1_linux_arm64.tar.gz"
        sha256 "a64e71271f1dc2c2a8a0e740804cdda60d7767927974901055a6bd06c793d974"

        def install
          bin.install "reme"
        end
      end
    end
  end
end
